package output

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/leandrotocalini/codelens/internal/graph"
	"github.com/leandrotocalini/codelens/internal/parser"
)

// Write generates the CODELENS.md file.
func Write(path string, commitHash string, projectSummary string, modules []parser.Module, summaries map[string]string, g *graph.Graph, stats parser.Stats) error {
	var sb strings.Builder

	// Header
	fmt.Fprintf(&sb, "<!-- Generated by CodeLens at commit %s — do not edit manually -->\n\n", commitHash)

	// Project Summary
	sb.WriteString("## Project Summary\n\n")
	if projectSummary != "" {
		sb.WriteString(projectSummary)
	} else {
		sb.WriteString("*No project summary available.*")
	}
	sb.WriteString("\n\n")

	// Module Map
	sb.WriteString("## Module Map\n\n")

	// Sort modules by name
	sortedModules := make([]parser.Module, len(modules))
	copy(sortedModules, modules)
	sort.Slice(sortedModules, func(i, j int) bool {
		return sortedModules[i].Name < sortedModules[j].Name
	})

	for _, m := range sortedModules {
		fmt.Fprintf(&sb, "### %s\n\n", m.Name)

		if summary, ok := summaries[m.Name]; ok && summary != "" {
			sb.WriteString(summary)
			sb.WriteString("\n")
		}

		// Dependencies
		if g != nil {
			deps := g.DependenciesOf(m.Name)
			if len(deps) > 0 {
				fmt.Fprintf(&sb, "**Depends on**: %s\n", strings.Join(deps, ", "))
			}
			usedBy := g.DependentsOf(m.Name)
			if len(usedBy) > 0 {
				fmt.Fprintf(&sb, "**Used by**: %s\n", strings.Join(usedBy, ", "))
			}
		}

		sb.WriteString("\n")
	}

	// Dependency Graph
	if g != nil && len(g.Modules) > 0 {
		sb.WriteString("## Dependency Graph\n\n")
		sb.WriteString("```\n")
		sb.WriteString(graph.Render(g))
		sb.WriteString("```\n\n")
	}

	// Stats
	sb.WriteString("## Stats\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")

	// Language breakdown
	if len(stats.LanguageBreakdown) > 0 {
		langStr := formatLanguages(stats.LanguageBreakdown, stats.TotalLOC)
		fmt.Fprintf(&sb, "| Languages | %s |\n", langStr)
	}
	fmt.Fprintf(&sb, "| Packages | %d |\n", stats.TotalPackages)
	fmt.Fprintf(&sb, "| Files | %d |\n", stats.TotalFiles)
	fmt.Fprintf(&sb, "| LOC | %s |\n", formatNumber(stats.TotalLOC))
	fmt.Fprintf(&sb, "| Exported functions | %d |\n", stats.ExportedFunctions)
	fmt.Fprintf(&sb, "| Exported types | %d |\n", stats.ExportedTypes)
	fmt.Fprintf(&sb, "| Indexed at | %s |\n", commitHash)

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func formatLanguages(breakdown map[string]int, totalLOC int) string {
	type langEntry struct {
		Name string
		LOC  int
	}

	var entries []langEntry
	for lang, loc := range breakdown {
		entries = append(entries, langEntry{Name: lang, LOC: loc})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].LOC > entries[j].LOC
	})

	var parts []string
	for _, e := range entries {
		pct := 0
		if totalLOC > 0 {
			pct = (e.LOC * 100) / totalLOC
		}
		if pct > 0 {
			parts = append(parts, fmt.Sprintf("%s (%d%%)", capitalize(e.Name), pct))
		}
	}

	return strings.Join(parts, ", ")
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	switch s {
	case "go":
		return "Go"
	case "java":
		return "Java"
	case "typescript":
		return "TypeScript"
	case "javascript":
		return "JavaScript"
	case "python":
		return "Python"
	case "rust":
		return "Rust"
	case "swift":
		return "Swift"
	default:
		return strings.ToUpper(s[:1]) + s[1:]
	}
}

func formatNumber(n int) string {
	if n < 1000 {
		return fmt.Sprintf("%d", n)
	}
	return fmt.Sprintf("%d,%03d", n/1000, n%1000)
}
