package output

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/leandrotocalini/codelens/internal/graph"
	"github.com/leandrotocalini/codelens/internal/parser"
)

func TestWrite(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, "CODELENS.md")

	modules := []parser.Module{
		{Name: "internal/handler", Language: "go"},
		{Name: "internal/model", Language: "go"},
	}

	summaries := map[string]string{
		"internal/handler": "**Responsibility**: Handles HTTP requests.\n**Key types**: Handler\n**Key functions**: New(), ServeHTTP()",
		"internal/model":   "**Responsibility**: Data models.\n**Key types**: User\n**Key functions**: NewUser(), Validate()",
	}

	g := graph.Build(modules)

	stats := parser.Stats{
		TotalFiles:        10,
		TotalLOC:          500,
		TotalPackages:     2,
		ExportedFunctions: 5,
		ExportedTypes:     3,
		LanguageBreakdown: map[string]int{"go": 500},
	}

	err := Write(outputPath, "abc123d", "This is a test project.", modules, summaries, g, stats)
	if err != nil {
		t.Fatalf("Write() error: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	text := string(content)

	// Check header
	if !strings.Contains(text, "Generated by CodeLens at commit abc123d") {
		t.Error("output should contain header with commit hash")
	}

	// Check project summary
	if !strings.Contains(text, "This is a test project.") {
		t.Error("output should contain project summary")
	}

	// Check module map
	if !strings.Contains(text, "### internal/handler") {
		t.Error("output should contain handler module")
	}
	if !strings.Contains(text, "### internal/model") {
		t.Error("output should contain model module")
	}

	// Check stats
	if !strings.Contains(text, "| Files | 10 |") {
		t.Error("output should contain file count")
	}
	if !strings.Contains(text, "| LOC | 500 |") {
		t.Error("output should contain LOC")
	}
	if !strings.Contains(text, "Go (100%)") {
		t.Error("output should contain language breakdown")
	}
}

func TestWriteIdempotent(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, "CODELENS.md")

	modules := []parser.Module{
		{Name: "pkg/a", Language: "go"},
		{Name: "pkg/b", Language: "go"},
	}

	summaries := map[string]string{
		"pkg/a": "Summary A",
		"pkg/b": "Summary B",
	}

	g := graph.Build(modules)
	stats := parser.Stats{TotalPackages: 2, LanguageBreakdown: map[string]int{"go": 100}}

	// Write twice
	if err := Write(outputPath, "abc", "Project.", modules, summaries, g, stats); err != nil {
		t.Fatal(err)
	}
	content1, _ := os.ReadFile(outputPath)

	if err := Write(outputPath, "abc", "Project.", modules, summaries, g, stats); err != nil {
		t.Fatal(err)
	}
	content2, _ := os.ReadFile(outputPath)

	if string(content1) != string(content2) {
		t.Error("output should be idempotent")
	}
}

func TestFormatLanguages(t *testing.T) {
	breakdown := map[string]int{
		"go":         800,
		"typescript": 200,
	}

	result := formatLanguages(breakdown, 1000)
	if !strings.Contains(result, "Go (80%)") {
		t.Errorf("expected 'Go (80%%)', got %q", result)
	}
	if !strings.Contains(result, "TypeScript (20%)") {
		t.Errorf("expected 'TypeScript (20%%)', got %q", result)
	}
}

func TestFormatNumber(t *testing.T) {
	tests := []struct {
		n    int
		want string
	}{
		{0, "0"},
		{999, "999"},
		{1000, "1,000"},
		{28419, "28,419"},
	}

	for _, tt := range tests {
		got := formatNumber(tt.n)
		if got != tt.want {
			t.Errorf("formatNumber(%d) = %q, want %q", tt.n, got, tt.want)
		}
	}
}
