package internal

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/leandrotocalini/codelens/internal/diff"
	"github.com/leandrotocalini/codelens/internal/graph"
	"github.com/leandrotocalini/codelens/internal/output"
	"github.com/leandrotocalini/codelens/internal/parser"
)

// MockSummarizer for integration tests.
type mockSummarizer struct{}

func (m *mockSummarizer) Summarize(_ context.Context, prompt string) (string, error) {
	if strings.Contains(prompt, "executive summary") || strings.Contains(prompt, "module summaries") {
		return "This is a test project that demonstrates the CodeLens pipeline. It contains multiple modules organized by language.", nil
	}
	return "**Responsibility**: Test module for integration testing.\n**Key types**: TestType\n**Key functions**: TestFunc()", nil
}

func TestFullPipeline(t *testing.T) {
	repoRoot := findTestdata(t, "go-project")

	// Step 1: Parse
	modules, stats, err := parser.Parse(repoRoot, []string{})
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if len(modules) == 0 {
		t.Fatal("no modules parsed")
	}
	if stats.TotalFiles == 0 {
		t.Fatal("no files found")
	}

	t.Logf("Parsed %d modules, %d files, %d LOC", stats.TotalPackages, stats.TotalFiles, stats.TotalLOC)

	// Step 2: Build dependency graph
	g := graph.Build(modules)
	if len(g.Modules) != len(modules) {
		t.Errorf("graph modules = %d, want %d", len(g.Modules), len(modules))
	}

	// Step 3: Summarize (with mock LLM)
	mock := &mockSummarizer{}
	summaries := make(map[string]string)
	for _, m := range modules {
		prompt := "test prompt for " + m.Name
		summary, err := mock.Summarize(context.Background(), prompt)
		if err != nil {
			t.Fatalf("Summarize() error: %v", err)
		}
		summaries[m.Name] = summary
	}

	// Project summary
	projectSummary, err := mock.Summarize(context.Background(), "executive summary")
	if err != nil {
		t.Fatalf("project summary error: %v", err)
	}

	// Step 4: Write output
	outputDir := t.TempDir()
	outputPath := filepath.Join(outputDir, "CODELENS.md")

	err = output.Write(outputPath, "test123", projectSummary, modules, summaries, g, stats, "")
	if err != nil {
		t.Fatalf("Write() error: %v", err)
	}

	// Verify output exists and has content
	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	text := string(content)
	if !strings.Contains(text, "Generated by CodeLens") {
		t.Error("output missing header")
	}
	if !strings.Contains(text, "Project Summary") {
		t.Error("output missing project summary section")
	}
	if !strings.Contains(text, "Runtime Module Map") {
		t.Error("output missing runtime module map section")
	}
	if !strings.Contains(text, "Stats") {
		t.Error("output missing stats section")
	}

	t.Logf("Generated CODELENS.md (%d bytes)", len(content))

	// Step 5: Save state
	err = diff.SaveState(outputDir, "abc123", "test-model", modules, summaries)
	if err != nil {
		t.Fatalf("SaveState() error: %v", err)
	}

	// Step 6: Load state back
	state, err := diff.LoadState(outputDir)
	if err != nil {
		t.Fatalf("LoadState() error: %v", err)
	}
	if state == nil {
		t.Fatal("state is nil after save")
	}
	if state.LastCommit != "abc123" {
		t.Errorf("LastCommit = %q, want %q", state.LastCommit, "abc123")
	}
	if len(state.Modules) != len(modules) {
		t.Errorf("state modules = %d, want %d", len(state.Modules), len(modules))
	}

	t.Log("Full pipeline integration test passed")
}

func TestMultiLanguagePipeline(t *testing.T) {
	testCases := []struct {
		name     string
		dir      string
		language string
	}{
		{"Go", "go-project", "go"},
		{"Java", "java-project", "java"},
		{"TypeScript", "ts-project", "typescript"},
		{"Python", "python-project", "python"},
		{"Swift", "swift-project", "swift"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			repoRoot := findTestdata(t, tc.dir)

			modules, stats, err := parser.Parse(repoRoot, []string{})
			if err != nil {
				t.Fatalf("Parse() error: %v", err)
			}

			if len(modules) == 0 {
				t.Fatal("no modules parsed")
			}
			if stats.TotalFiles == 0 {
				t.Fatal("no files found")
			}

			// Verify language
			foundLang := false
			for _, m := range modules {
				if m.Language == tc.language {
					foundLang = true
					break
				}
			}
			if !foundLang {
				t.Errorf("no modules with language %q", tc.language)
			}

			// Build graph and verify
			g := graph.Build(modules)
			if len(g.Modules) == 0 {
				t.Error("empty graph")
			}

			// Render graph
			rendered := graph.Render(g)
			if rendered == "" {
				t.Error("empty render output")
			}

			t.Logf("%s: %d modules, %d files, %d LOC", tc.name, stats.TotalPackages, stats.TotalFiles, stats.TotalLOC)
		})
	}
}

func TestIncrementalPipeline(t *testing.T) {
	repoRoot := findTestdata(t, "go-project")
	stateDir := t.TempDir()

	// Step 1: Full index
	modules, _, err := parser.Parse(repoRoot, []string{})
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	summaries := make(map[string]string)
	for _, m := range modules {
		summaries[m.Name] = "Summary for " + m.Name
	}

	err = diff.SaveState(stateDir, "commit1", "test-model", modules, summaries)
	if err != nil {
		t.Fatalf("SaveState() error: %v", err)
	}

	// Step 2: Load state and check
	state, err := diff.LoadState(stateDir)
	if err != nil {
		t.Fatalf("LoadState() error: %v", err)
	}
	if state.LastCommit != "commit1" {
		t.Errorf("LastCommit = %q, want %q", state.LastCommit, "commit1")
	}

	// Step 3: Simulate changed files
	changedFiles := []string{modules[0].Files[0].Path}
	affected := diff.AffectedModules(changedFiles, modules)
	if len(affected) != 1 {
		t.Errorf("affected = %d, want 1", len(affected))
	}

	// Step 4: Re-parse and verify summaries are preserved
	_, _, err = parser.Parse(repoRoot, []string{})
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	// Cached summaries should still be available
	for _, m := range modules {
		if _, ok := state.Summaries[m.Name]; !ok {
			t.Errorf("missing cached summary for %s", m.Name)
		}
	}

	t.Log("Incremental pipeline test passed")
}

func findTestdata(t *testing.T, project string) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		td := filepath.Join(dir, "testdata", project)
		if info, err := os.Stat(td); err == nil && info.IsDir() {
			return td
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("testdata/%s not found", project)
		}
		dir = parent
	}
}
